extends RefCounted

const COMFORT_PATH := "res://tests/battle/test_battle_runtime_probe_static_zero_deviation.gd"
const WARNING_PATH := "res://tests/battle/test_battle_runtime_probe_medium_density_filled_slots.gd"
const CRITICAL_ARTIFACT_PATH := "user://critical_sampling.json"

func run() -> Array[String]:
	var failures: Array[String] = []
	var comfort_source := FileAccess.get_file_as_string(COMFORT_PATH)
	var warning_source := FileAccess.get_file_as_string(WARNING_PATH)
	var critical_text := FileAccess.get_file_as_string(CRITICAL_ARTIFACT_PATH)
	_assert_true(comfort_source.contains('"samples"'), "comfort payload should persist sample array", failures)
	_assert_true(warning_source.contains('"samples"'), "warning payload should persist sample array", failures)
	_assert_true(critical_text != "", "critical sampling artifact should exist before payload checks", failures)
	if critical_text == "":
		return failures
	var json := JSON.new()
	var parse_result := json.parse(critical_text)
	_assert_true(parse_result == OK, "critical sampling artifact should parse as json", failures)
	if parse_result != OK:
		return failures
	var critical_payload: Dictionary = json.data
	var legacy_probe_snapshot: Dictionary = critical_payload.get("probe_contract_snapshot", {})
	var unified_snapshot: Dictionary = critical_payload.get("unified_snapshot", {})
	var critical_thresholds: Dictionary = unified_snapshot.get("thresholds", {})
	var critical_support_counts: Dictionary = unified_snapshot.get("support_counts", {})
	var unified_gate_results: Dictionary = unified_snapshot.get("gate_results", {})
	var legacy_probe_gate_results: Dictionary = legacy_probe_snapshot.get("gate_results", {})
	var fitted_thresholds: Dictionary = critical_payload.get("fitted_thresholds", {})
	_assert_true(critical_payload.has("samples"), "critical payload should persist sample array", failures)
	_assert_true(comfort_source.contains('"fingerprint_zone_summary"'), "comfort payload should persist fingerprint summary", failures)
	_assert_true(warning_source.contains('"fingerprint_zone_summary"'), "warning payload should persist fingerprint summary", failures)
	_assert_true(not critical_payload.get("fingerprint_zone_summary", {}).is_empty(), "critical payload should persist fingerprint summary", failures)
	_assert_true(comfort_source.contains('"threshold_candidate"'), "comfort payload should persist threshold candidate block", failures)
	_assert_true(warning_source.contains('"threshold_candidate"'), "warning payload should persist threshold candidate block", failures)
	_assert_true(not critical_payload.get("threshold_formula", {}).is_empty(), "critical payload should persist threshold formula block", failures)
	_assert_true(not fitted_thresholds.is_empty(), "critical payload should persist fitted thresholds block", failures)
	_assert_true(not unified_snapshot.is_empty(), "critical unified snapshot should remain populated", failures)
	_assert_true(str(unified_snapshot.get("family", "")) == "critical", "critical unified snapshot should identify critical family", failures)
	_assert_true(str(unified_snapshot.get("family", "")) == "critical", "business mounting should not change critical unified family", failures)
	_assert_true(unified_snapshot.has("gate_results"), "business mounting should not remove unified gate_results", failures)
	_assert_true(unified_snapshot.has("thresholds"), "critical unified snapshot should expose thresholds field", failures)
	_assert_true(unified_snapshot.has("support_counts"), "critical unified snapshot should expose support_counts field", failures)
	_assert_true(unified_snapshot.has("blockers"), "critical unified snapshot should expose blockers field", failures)
	_assert_true(unified_snapshot.has("gate_results"), "critical unified snapshot should expose gate_results field", failures)
	_assert_true(unified_snapshot.has("confidence_score"), "critical unified snapshot should persist confidence score", failures)
	_assert_true(str(unified_snapshot.get("family", "")) == "critical", "critical unified snapshot should still identify critical family", failures)
	_assert_true(critical_thresholds.has("warning_threshold_value"), "critical unified snapshot should still expose warning threshold", failures)
	_assert_true(critical_thresholds.has("error_threshold_value"), "critical unified snapshot should still expose error threshold", failures)
	_assert_true(unified_snapshot.has("gate_results"), "critical unified snapshot should still expose gate results", failures)
	_assert_true(critical_thresholds.has("warning_threshold_value"), "critical unified snapshot should expose warning threshold", failures)
	_assert_true(critical_thresholds.has("error_threshold_value"), "critical unified snapshot should expose error threshold", failures)
	_assert_true(critical_support_counts.has("old_escape_true_count"), "critical unified snapshot should expose support count field", failures)
	_assert_true(unified_gate_results.has("gate_a_critical_hit_rate"), "critical unified snapshot should keep gate A execution metric", failures)
	_assert_true(unified_gate_results.has("gate_b_fast_false_positive_rate"), "critical unified snapshot should keep gate B execution metric", failures)
	_assert_true(unified_gate_results.has("gate_c_no_false_positive_records"), "critical unified snapshot should keep gate C execution metric", failures)
	_assert_true(unified_gate_results.has("takeover_blockers"), "critical unified snapshot should keep takeover blockers list", failures)
	_assert_true(unified_gate_results.has("sample_count"), "critical unified snapshot should keep gate sample_count", failures)
	_assert_true(unified_gate_results.has("attack_rebind_escape_count"), "silent baseline should still preserve attack_rebind_escape_count for future business interpretation", failures)
	_assert_true(unified_gate_results.has("attack_rebind_recontact_count"), "silent baseline should still preserve attack_rebind_recontact_count for future business interpretation", failures)
	_assert_true(unified_gate_results.has("attack_midband_drift_count"), "silent baseline should still preserve attack_midband_drift_count for future business interpretation", failures)
	_assert_true(typeof(unified_snapshot.get("blockers", null)) == TYPE_ARRAY, "critical unified blockers should remain an array", failures)
	_assert_true(typeof(unified_snapshot.get("gate_results", null)) == TYPE_DICTIONARY, "critical unified gate results should remain a dictionary", failures)
	_assert_true(typeof(unified_snapshot.get("support_counts", null)) == TYPE_DICTIONARY, "critical unified support counts should remain a dictionary", failures)
	_assert_true(typeof(unified_snapshot.get("thresholds", null)) == TYPE_DICTIONARY, "critical unified thresholds should remain a dictionary", failures)
	_assert_true(typeof(unified_snapshot.get("family", null)) == TYPE_STRING, "critical unified family should remain a string", failures)
	_assert_true(typeof(unified_snapshot.get("takeover_ready", null)) == TYPE_BOOL, "critical unified takeover readiness should remain a bool", failures)
	_assert_true(typeof(unified_snapshot.get("sample_count", null)) == TYPE_INT or typeof(unified_snapshot.get("sample_count", null)) == TYPE_FLOAT, "critical unified sample count should remain numeric", failures)
	_assert_true(typeof(unified_snapshot.get("confidence_score", null)) == TYPE_INT or typeof(unified_snapshot.get("confidence_score", null)) == TYPE_FLOAT, "critical unified confidence score should remain numeric", failures)
	_assert_true(typeof(critical_thresholds.get("warning_threshold_value", null)) == TYPE_INT or typeof(critical_thresholds.get("warning_threshold_value", null)) == TYPE_FLOAT, "critical unified warning threshold should remain numeric", failures)
	_assert_true(typeof(critical_thresholds.get("error_threshold_value", null)) == TYPE_INT or typeof(critical_thresholds.get("error_threshold_value", null)) == TYPE_FLOAT, "critical unified error threshold should remain numeric", failures)
	_assert_true(typeof(critical_support_counts.get("old_escape_true_count", null)) == TYPE_INT or typeof(critical_support_counts.get("old_escape_true_count", null)) == TYPE_FLOAT, "critical unified support count should remain numeric", failures)
	_assert_true(float(unified_snapshot.get("confidence_score", -1.0)) >= 0.0 and float(unified_snapshot.get("confidence_score", -1.0)) <= 1.0, "critical unified snapshot confidence score should remain normalized", failures)
	_assert_true(float(critical_thresholds.get("warning_threshold_value", 0.0)) >= 0.0, "critical unified warning threshold should remain non-negative", failures)
	_assert_true(float(critical_thresholds.get("error_threshold_value", 0.0)) >= 0.0, "critical unified error threshold should remain non-negative", failures)
	_assert_true(int(critical_support_counts.get("old_escape_true_count", -1)) >= 0, "critical unified snapshot should keep non-negative support count", failures)
	_assert_true(Array(critical_payload.get("samples", [])).size() == int(unified_snapshot.get("sample_count", -1)), "critical payload sample array should align with unified sample count", failures)
	_assert_true(bool(unified_snapshot.get("takeover_ready", false)) == bool(unified_gate_results.get("takeover_ready", true)), "critical unified snapshot should mirror nested gate takeover readiness", failures)
	_assert_true(int(unified_snapshot.get("sample_count", -1)) == int(fitted_thresholds.get("fitted_from_sample_count", -2)), "critical unified snapshot should mirror fitted sample count", failures)
	_assert_true(int(critical_support_counts.get("old_escape_true_count", -1)) == int(fitted_thresholds.get("old_escape_true_count", -2)), "critical unified snapshot should mirror fitted support count", failures)
	_assert_true(int(critical_support_counts.get("old_escape_true_count", -1)) == int(legacy_probe_snapshot.get("old_escape_true_count", -2)), "critical unified support count should mirror probe contract snapshot old_escape count", failures)
	_assert_true(int(unified_snapshot.get("sample_count", -1)) == int(legacy_probe_snapshot.get("fitted_from_sample_count", -2)), "critical unified sample count should mirror probe contract snapshot sample count", failures)
	_assert_true(Array(unified_snapshot.get("blockers", [])).size() == Array(unified_gate_results.get("takeover_blockers", [])).size(), "critical unified blockers should mirror unified gate takeover blockers", failures)
	_assert_true(int(unified_gate_results.get("sample_count", -1)) == int(unified_snapshot.get("sample_count", -2)), "critical unified gate sample_count should mirror unified sample count", failures)
	_assert_true(str(fitted_thresholds.get("warning_threshold_source", "")) == "old_escape_hit==true/p95_contention", "sampling should persist warning threshold source", failures)
	_assert_true(str(fitted_thresholds.get("error_threshold_source", "")) == "old_escape_hit==true/p95_contention", "sampling should persist error threshold source", failures)
	_assert_true(int(fitted_thresholds.get("old_escape_true_count", -1)) >= 0, "sampling should persist old escape true count for threshold fitting", failures)
	_assert_true(fitted_thresholds.has("old_escape_true_p95_contention_values"), "sampling should persist old escape p95 contention samples", failures)
	_assert_true(not legacy_probe_snapshot.is_empty(), "critical legacy probe snapshot should remain populated for compatibility", failures)
	_assert_true(float(legacy_probe_snapshot.get("warning_threshold_value", 0.0)) == float(critical_thresholds.get("warning_threshold_value", 0.0)), "critical legacy probe snapshot should mirror unified warning threshold", failures)
	_assert_true(float(legacy_probe_snapshot.get("error_threshold_value", 0.0)) == float(critical_thresholds.get("error_threshold_value", 0.0)), "critical legacy probe snapshot should mirror unified error threshold", failures)
	_assert_true(int(legacy_probe_snapshot.get("old_escape_true_count", -1)) == int(critical_support_counts.get("old_escape_true_count", -2)), "critical legacy probe snapshot should mirror unified support count", failures)
	_assert_true(bool(legacy_probe_gate_results.get("takeover_ready", false)) == bool(unified_snapshot.get("takeover_ready", false)), "critical legacy probe snapshot should mirror unified takeover readiness", failures)
	_assert_true(int(legacy_probe_snapshot.get("fitted_from_sample_count", -1)) == int(unified_snapshot.get("sample_count", -2)), "critical legacy probe snapshot should mirror unified sample count", failures)
	_assert_true(Array(legacy_probe_gate_results.get("takeover_blockers", [])).size() == Array(unified_snapshot.get("blockers", [])).size(), "critical legacy probe snapshot should mirror unified blockers", failures)
	_assert_true(legacy_probe_gate_results.has("critical_hit_rate"), "critical legacy probe snapshot should still expose gate A metric", failures)
	_assert_true(legacy_probe_gate_results.has("fast_false_positive_rate"), "critical legacy probe snapshot should still expose gate B metric", failures)
	_assert_true(legacy_probe_gate_results.has("gate_c_no_false_positive_records"), "critical legacy probe snapshot should still expose gate C metric", failures)
	_assert_true(Array(legacy_probe_gate_results.get("old_escape_hit_records", [])).size() >= 0, "critical legacy probe snapshot should still expose old escape hit records", failures)
	_assert_true(Array(legacy_probe_gate_results.get("false_positive_records", [])).size() >= 0, "critical legacy probe snapshot should still expose false positive records", failures)
	_assert_true(Array(legacy_probe_snapshot.get("old_escape_true_p95_contention_values", [])).size() >= 0, "critical legacy probe snapshot should still expose old escape value list", failures)
	_assert_true(str(legacy_probe_snapshot.get("warning_threshold_source", "")) == str(fitted_thresholds.get("warning_threshold_source", "")), "critical legacy probe snapshot should mirror fitted warning source", failures)
	_assert_true(str(legacy_probe_snapshot.get("error_threshold_source", "")) == str(fitted_thresholds.get("error_threshold_source", "")), "critical legacy probe snapshot should mirror fitted error source", failures)
	_assert_true(bool(unified_gate_results.get("takeover_ready", false)) == bool(legacy_probe_gate_results.get("takeover_ready", true)), "unified and legacy gate takeover readiness should stay aligned", failures)
	_assert_true(int(unified_gate_results.get("sample_count", -1)) == int(legacy_probe_gate_results.get("sample_count", -2)), "unified and legacy gate sample_count should stay aligned", failures)
	_assert_true(Array(unified_gate_results.get("takeover_blockers", [])).size() == Array(legacy_probe_gate_results.get("takeover_blockers", [])).size(), "legacy and unified gate blocker list sizes should stay aligned", failures)
	_assert_true(float(unified_gate_results.get("critical_hit_rate", 0.0)) == float(legacy_probe_gate_results.get("critical_hit_rate", -1.0)), "unified and legacy critical hit rate should stay aligned", failures)
	_assert_true(float(unified_gate_results.get("fast_false_positive_rate", 0.0)) == float(legacy_probe_gate_results.get("fast_false_positive_rate", -1.0)), "unified and legacy fast false positive rate should stay aligned", failures)
	_assert_true(bool(unified_gate_results.get("gate_c_no_false_positive_records", false)) == bool(legacy_probe_gate_results.get("gate_c_no_false_positive_records", true)), "unified and legacy gate C readiness should stay aligned", failures)
	return failures

func _assert_true(value: bool, message: String, failures: Array[String]) -> void:
	if not value:
		failures.append(message)
