extends RefCounted

const ARTIFACT_PATH := "user://critical_sampling.json"

func run() -> Array[String]:
	var failures: Array[String] = []
	var text := FileAccess.get_file_as_string(ARTIFACT_PATH)
	_assert_true(text != "", "critical sampling artifact should exist before fitted threshold checks", failures)
	if text == "":
		return failures
	var json := JSON.new()
	var parse_result := json.parse(text)
	_assert_true(parse_result == OK, "critical sampling artifact should parse as json", failures)
	if parse_result != OK:
		return failures
	var payload: Dictionary = json.data
	var fitted_thresholds: Dictionary = payload.get("fitted_thresholds", {})
	var legacy_probe_snapshot: Dictionary = payload.get("probe_contract_snapshot", {})
	var unified_snapshot: Dictionary = payload.get("unified_snapshot", {})
	var thresholds: Dictionary = unified_snapshot.get("thresholds", {})
	var unified_support_counts: Dictionary = unified_snapshot.get("support_counts", {})
	var unified_gate_results: Dictionary = unified_snapshot.get("gate_results", {})
	var probe_gate_results: Dictionary = legacy_probe_snapshot.get("gate_results", {})
	var unified_warning_threshold := float(thresholds.get("warning_threshold_value", 0.0))
	var unified_error_threshold := float(thresholds.get("error_threshold_value", 0.0))
	var unified_sample_count := int(unified_snapshot.get("sample_count", -1))
	var unified_takeover_ready := bool(unified_snapshot.get("takeover_ready", false))
	var unified_confidence_score := float(unified_snapshot.get("confidence_score", -1.0))
	var old_escape_true_count := int(unified_support_counts.get("old_escape_true_count", -1))
	var legacy_warning_threshold := float(legacy_probe_snapshot.get("warning_threshold_value", 0.0))
	var legacy_error_threshold := float(legacy_probe_snapshot.get("error_threshold_value", 0.0))
	var legacy_sample_count := int(legacy_probe_snapshot.get("fitted_from_sample_count", -1))
	var legacy_old_escape_true_count := int(legacy_probe_snapshot.get("old_escape_true_count", -1))
	var legacy_warning_threshold_source := str(legacy_probe_snapshot.get("warning_threshold_source", ""))
	var legacy_error_threshold_source := str(legacy_probe_snapshot.get("error_threshold_source", ""))
	var warning_threshold_source := str(fitted_thresholds.get("warning_threshold_source", ""))
	var error_threshold_source := str(fitted_thresholds.get("error_threshold_source", ""))
	var fitted_old_escape_values: Array = fitted_thresholds.get("old_escape_true_p95_contention_values", [])
	var legacy_old_escape_values: Array = legacy_probe_snapshot.get("old_escape_true_p95_contention_values", [])
	_assert_true(not unified_snapshot.is_empty(), "critical unified snapshot should remain populated", failures)
	_assert_true(str(unified_snapshot.get("family", "")) == "critical", "critical unified snapshot should identify critical family", failures)
	_assert_has_keys(unified_snapshot, ["thresholds", "support_counts", "blockers", "gate_results"], "critical unified snapshot should expose", failures)
	_assert_has_keys(thresholds, ["warning_threshold_value", "error_threshold_value"], "critical unified snapshot should expose", failures)
	_assert_has_keys(unified_support_counts, ["old_escape_true_count"], "critical unified snapshot should expose", failures)
	_assert_has_keys(unified_gate_results, ["gate_a_critical_hit_rate", "gate_b_fast_false_positive_rate", "gate_c_no_false_positive_records", "takeover_blockers", "sample_count"], "critical unified snapshot should keep", failures)
	_assert_numeric_or_int(unified_snapshot.get("sample_count", null), "critical unified sample count should remain numeric", failures)
	_assert_true(typeof(unified_snapshot.get("takeover_ready", null)) == TYPE_BOOL, "critical unified takeover_ready should remain a bool", failures)
	_assert_true(typeof(unified_snapshot.get("family", null)) == TYPE_STRING, "critical unified family should remain a string", failures)
	_assert_numeric_or_int(unified_snapshot.get("confidence_score", null), "critical unified confidence score should remain numeric", failures)
	_assert_true(typeof(unified_snapshot.get("thresholds", null)) == TYPE_DICTIONARY, "critical unified thresholds should remain a dictionary", failures)
	_assert_true(typeof(unified_snapshot.get("support_counts", null)) == TYPE_DICTIONARY, "critical unified support counts should remain a dictionary", failures)
	_assert_true(typeof(unified_snapshot.get("gate_results", null)) == TYPE_DICTIONARY, "critical unified gate results should remain a dictionary", failures)
	_assert_true(typeof(unified_snapshot.get("blockers", null)) == TYPE_ARRAY, "critical unified blockers should remain an array", failures)
	_assert_numeric_or_int(thresholds.get("warning_threshold_value", null), "critical unified warning threshold should remain numeric", failures)
	_assert_numeric_or_int(thresholds.get("error_threshold_value", null), "critical unified error threshold should remain numeric", failures)
	_assert_numeric_or_int(unified_support_counts.get("old_escape_true_count", null), "critical unified support count should remain numeric", failures)
	_assert_true(float(unified_warning_threshold) >= 0.0, "critical unified warning threshold should remain non-negative", failures)
	_assert_true(float(unified_error_threshold) >= 0.0, "critical unified error threshold should remain non-negative", failures)
	_assert_true(unified_confidence_score >= 0.0 and unified_confidence_score <= 1.0, "critical unified confidence score should remain normalized", failures)
	_assert_true(old_escape_true_count >= 0, "critical unified snapshot should keep non-negative support count", failures)
	_assert_true(float(legacy_probe_snapshot.get("warning_threshold_value", 0.0)) == float(fitted_thresholds.get("warning_threshold_value", 0.0)), "critical snapshot warning threshold should mirror fitted warning threshold", failures)
	_assert_true(float(legacy_probe_snapshot.get("error_threshold_value", 0.0)) == float(fitted_thresholds.get("error_threshold_value", 0.0)), "critical snapshot error threshold should mirror fitted error threshold", failures)
	_assert_true(unified_warning_threshold == float(fitted_thresholds.get("warning_threshold_value", 0.0)), "critical unified snapshot should mirror warning threshold value", failures)
	_assert_true(unified_error_threshold == float(fitted_thresholds.get("error_threshold_value", 0.0)), "critical unified snapshot should mirror error threshold value", failures)
	_assert_true(unified_warning_threshold == float(legacy_probe_snapshot.get("warning_threshold_value", 0.0)), "critical unified warning threshold should mirror probe contract snapshot", failures)
	_assert_true(unified_error_threshold == float(legacy_probe_snapshot.get("error_threshold_value", 0.0)), "critical unified error threshold should mirror probe contract snapshot", failures)
	_assert_true(unified_sample_count == int(fitted_thresholds.get("fitted_from_sample_count", -2)), "critical unified snapshot should mirror fitted threshold sample count", failures)
	_assert_true(old_escape_true_count == int(fitted_thresholds.get("old_escape_true_count", -2)), "critical unified snapshot should mirror fitted support count", failures)
	_assert_true(bool(unified_snapshot.get("takeover_ready", false)) == bool(unified_gate_results.get("takeover_ready", true)), "critical unified snapshot should mirror nested gate takeover readiness", failures)
	_assert_true(int(unified_gate_results.get("sample_count", -1)) == unified_sample_count, "critical unified gate sample_count should mirror unified sample count", failures)
	_assert_true(Array(unified_snapshot.get("blockers", [])).size() == Array(unified_gate_results.get("takeover_blockers", [])).size(), "critical unified blockers should mirror unified gate takeover blockers", failures)
	_assert_true(str(fitted_thresholds.get("warning_threshold_source", "")) == "old_escape_hit==true/p95_contention", "sampling should persist warning threshold source", failures)
	_assert_true(str(fitted_thresholds.get("error_threshold_source", "")) == "old_escape_hit==true/p95_contention", "sampling should persist error threshold source", failures)
	_assert_true(fitted_thresholds.has("old_escape_true_p95_contention_values"), "sampling should persist old escape p95 contention samples", failures)
	_assert_true(int(fitted_thresholds.get("old_escape_true_count", -1)) >= 0, "sampling should persist old escape true count for threshold fitting", failures)
	_assert_true(not legacy_probe_snapshot.is_empty(), "probe contract snapshot should remain populated for compatibility", failures)
	_assert_has_keys(legacy_probe_snapshot, ["gate_results", "warning_threshold_value", "error_threshold_value", "fitted_from_sample_count", "old_escape_true_count", "warning_threshold_source", "error_threshold_source", "old_escape_true_p95_contention_values"], "probe contract snapshot should keep", failures)
	_assert_has_keys(probe_gate_results, ["critical_hit_rate", "fast_false_positive_rate", "gate_c_no_false_positive_records", "takeover_ready", "sample_count", "takeover_blockers", "old_escape_hit_records", "false_positive_records"], "probe contract snapshot should keep", failures)
	_assert_numeric_or_int(legacy_probe_snapshot.get("warning_threshold_value", null), "probe contract warning threshold should remain numeric", failures)
	_assert_numeric_or_int(legacy_probe_snapshot.get("error_threshold_value", null), "probe contract error threshold should remain numeric", failures)
	_assert_numeric_or_int(legacy_probe_snapshot.get("fitted_from_sample_count", null), "probe contract sample count should remain numeric", failures)
	_assert_numeric_or_int(legacy_probe_snapshot.get("old_escape_true_count", null), "probe contract support count should remain numeric", failures)
	_assert_true(typeof(legacy_probe_snapshot.get("warning_threshold_source", null)) == TYPE_STRING, "probe contract warning source should remain a string", failures)
	_assert_true(typeof(legacy_probe_snapshot.get("error_threshold_source", null)) == TYPE_STRING, "probe contract error source should remain a string", failures)
	_assert_true(typeof(legacy_probe_snapshot.get("old_escape_true_p95_contention_values", null)) == TYPE_ARRAY, "probe contract old escape value list should remain an array", failures)
	_assert_true(typeof(legacy_probe_snapshot.get("gate_results", null)) == TYPE_DICTIONARY, "probe contract gate results should remain a dictionary", failures)
	_assert_true(legacy_warning_threshold >= 0.0, "probe contract warning threshold should stay non-negative", failures)
	_assert_true(legacy_error_threshold >= 0.0, "probe contract error threshold should stay non-negative", failures)
	_assert_true(legacy_sample_count >= 0, "probe contract sample count should stay non-negative", failures)
	_assert_true(legacy_old_escape_true_count >= 0, "probe contract snapshot support count should stay non-negative", failures)
	_assert_true(legacy_warning_threshold == unified_warning_threshold, "probe contract snapshot should mirror unified warning threshold value", failures)
	_assert_true(legacy_error_threshold == unified_error_threshold, "probe contract snapshot should mirror unified error threshold value", failures)
	_assert_true(legacy_sample_count == unified_sample_count, "probe contract snapshot should mirror unified sample count", failures)
	_assert_true(legacy_old_escape_true_count == old_escape_true_count, "probe contract snapshot should mirror unified support count", failures)
	_assert_true(bool(probe_gate_results.get("takeover_ready", false)) == unified_takeover_ready, "probe contract snapshot should mirror unified takeover readiness", failures)
	_assert_true(Array(probe_gate_results.get("takeover_blockers", [])).size() == Array(unified_snapshot.get("blockers", [])).size(), "probe contract snapshot blocker count should mirror unified blockers", failures)
	_assert_true(legacy_warning_threshold == float(fitted_thresholds.get("warning_threshold_value", 0.0)), "probe contract warning threshold should stay compatible with fitted source value", failures)
	_assert_true(legacy_error_threshold == float(fitted_thresholds.get("error_threshold_value", 0.0)), "probe contract error threshold should stay compatible with fitted source value", failures)
	_assert_true(legacy_sample_count == int(fitted_thresholds.get("fitted_from_sample_count", -1)), "probe contract sample count should stay compatible with fitted source count", failures)
	_assert_true(legacy_old_escape_true_count == int(fitted_thresholds.get("old_escape_true_count", -1)), "probe contract support count should stay compatible with fitted source count", failures)
	_assert_true(legacy_warning_threshold_source == warning_threshold_source, "probe contract snapshot should mirror fitted warning source", failures)
	_assert_true(legacy_error_threshold_source == error_threshold_source, "probe contract snapshot should mirror fitted error source", failures)
	_assert_true(Array(legacy_old_escape_values).size() == Array(fitted_old_escape_values).size(), "probe contract old escape list size should stay compatible with fitted source", failures)
	_assert_true(bool(unified_gate_results.get("takeover_ready", false)) == bool(probe_gate_results.get("takeover_ready", true)), "unified and legacy gate takeover readiness should stay aligned", failures)
	_assert_true(int(unified_gate_results.get("sample_count", -1)) == int(probe_gate_results.get("sample_count", -2)), "unified and legacy gate sample_count should stay aligned", failures)
	_assert_true(Array(unified_gate_results.get("takeover_blockers", [])).size() == Array(probe_gate_results.get("takeover_blockers", [])).size(), "unified and legacy gate blocker list sizes should stay aligned", failures)
	_assert_true(Array(unified_gate_results.get("old_escape_hit_records", [])).size() == Array(probe_gate_results.get("old_escape_hit_records", [])).size(), "unified and legacy old escape hit record sizes should stay aligned", failures)
	_assert_true(Array(unified_gate_results.get("false_positive_records", [])).size() == Array(probe_gate_results.get("false_positive_records", [])).size(), "unified and legacy false positive record sizes should stay aligned", failures)
	_assert_true(float(unified_gate_results.get("critical_hit_rate", 0.0)) == float(probe_gate_results.get("critical_hit_rate", -1.0)), "unified and legacy critical hit rate should stay aligned", failures)
	_assert_true(float(unified_gate_results.get("fast_false_positive_rate", 0.0)) == float(probe_gate_results.get("fast_false_positive_rate", -1.0)), "unified and legacy fast false positive rate should stay aligned", failures)
	_assert_true(bool(unified_gate_results.get("gate_c_no_false_positive_records", false)) == bool(probe_gate_results.get("gate_c_no_false_positive_records", true)), "unified and legacy gate C readiness should stay aligned", failures)
	return failures

func _assert_has_keys(dict: Dictionary, keys: Array, prefix: String, failures: Array[String]) -> void:
	for key in keys:
		_assert_true(dict.has(key), "%s %s" % [prefix, str(key)], failures)

func _assert_numeric_or_int(value: Variant, message: String, failures: Array[String]) -> void:
	_assert_true(typeof(value) == TYPE_FLOAT or typeof(value) == TYPE_INT, message, failures)

func _assert_true(value: bool, message: String, failures: Array[String]) -> void:
	if not value:
		failures.append(message)
