extends RefCounted

const ARTIFACT_PATH := "user://warning_sampling.json"

func run() -> Array[String]:
	var failures: Array[String] = []
	var text := FileAccess.get_file_as_string(ARTIFACT_PATH)
	_assert_true(text != "", "warning sampling artifact should exist before content checks", failures)
	if text == "":
		return failures
	var json := JSON.new()
	var parse_result := json.parse(text)
	_assert_true(parse_result == OK, "warning sampling artifact should parse as json", failures)
	if parse_result != OK:
		return failures
	var payload: Dictionary = json.data
	var scenario_summaries: Dictionary = payload.get("scenario_summaries", {})
	var threshold_candidate: Dictionary = payload.get("threshold_candidate", {})
	var fitted_thresholds: Dictionary = payload.get("fitted_thresholds", {})
	var gate_results: Dictionary = payload.get("gate_results", {})
	var legacy_readiness_snapshot: Dictionary = payload.get("readiness_snapshot", {})
	var unified_snapshot: Dictionary = payload.get("unified_snapshot", {})
	var unified_thresholds: Dictionary = unified_snapshot.get("thresholds", {})
	var unified_support_counts: Dictionary = unified_snapshot.get("support_counts", {})
	var unified_gate_results: Dictionary = unified_snapshot.get("gate_results", {})
	var legacy_readiness_family := str(legacy_readiness_snapshot.get("family", ""))
	var legacy_readiness_sample_count := int(legacy_readiness_snapshot.get("sample_count", -1))
	var legacy_readiness_nonzero_scenario_count := int(legacy_readiness_snapshot.get("nonzero_scenario_count", -1))
	var legacy_readiness_takeover_ready := bool(legacy_readiness_snapshot.get("takeover_ready", false))
	var legacy_readiness_warning_upper_threshold := float(legacy_readiness_snapshot.get("warning_upper_threshold_value", 0.0))
	var legacy_readiness_warning_threshold := float(legacy_readiness_snapshot.get("warning_threshold_value", 0.0))
	var legacy_readiness_warning_lower_threshold := float(legacy_readiness_snapshot.get("warning_lower_threshold_value", 0.0))
	var unified_sample_count := int(unified_snapshot.get("sample_count", -1))
	var unified_nonzero_scenario_count := int(unified_support_counts.get("nonzero_scenario_count", -1))
	var unified_takeover_ready := bool(unified_snapshot.get("takeover_ready", false))
	var unified_warning_upper_threshold := float(unified_thresholds.get("warning_upper_threshold_value", 0.0))
	var unified_warning_threshold := float(unified_thresholds.get("warning_threshold_value", 0.0))
	var unified_warning_lower_threshold := float(unified_thresholds.get("warning_lower_threshold_value", 0.0))
	var warning_summary: Dictionary = payload.get("warning_summary", {})
	var corridor_summary: Dictionary = scenario_summaries.get("corridor", {})
	var funnel_summary: Dictionary = scenario_summaries.get("funnel", {})
	var orbit_summary: Dictionary = scenario_summaries.get("dynamic_orbit", {})
	var sampling_results: Dictionary = payload.get("sampling_results", {})
	_assert_true(not corridor_summary.is_empty(), "warning artifact should persist corridor summary", failures)
	_assert_true(not funnel_summary.is_empty(), "warning artifact should persist funnel summary", failures)
	_assert_true(not orbit_summary.is_empty(), "warning artifact should persist dynamic_orbit summary", failures)
	_assert_true(float(corridor_summary.get("p95_contention_mean", 0.0)) > float(funnel_summary.get("p95_contention_mean", 0.0)) and float(funnel_summary.get("p95_contention_mean", 0.0)) > float(orbit_summary.get("p95_contention_mean", 0.0)), "warning artifact should preserve p95 ordering in scenario summaries", failures)
	_assert_true(float(corridor_summary.get("conflict_overlap_count_mean", 0.0)) > float(funnel_summary.get("conflict_overlap_count_mean", 0.0)) and float(funnel_summary.get("conflict_overlap_count_mean", 0.0)) > float(orbit_summary.get("conflict_overlap_count_mean", 0.0)), "warning artifact should preserve overlap ordering in scenario summaries", failures)
	_assert_true(float(corridor_summary.get("clumping_factor_mean", 0.0)) > float(funnel_summary.get("clumping_factor_mean", 0.0)) and float(funnel_summary.get("clumping_factor_mean", 0.0)) > float(orbit_summary.get("clumping_factor_mean", 0.0)), "warning artifact should preserve clumping ordering in scenario summaries", failures)
	_assert_true(float(orbit_summary.get("late_commit_deviation_mean", 0.0)) > float(funnel_summary.get("late_commit_deviation_mean", 0.0)) and float(funnel_summary.get("late_commit_deviation_mean", 0.0)) > float(corridor_summary.get("late_commit_deviation_mean", 0.0)), "warning artifact should preserve late commit deviation ordering in scenario summaries", failures)
	_assert_true(float(orbit_summary.get("late_commit_deviation_mean", 0.0)) - float(corridor_summary.get("late_commit_deviation_mean", 0.0)) > 0.7, "warning artifact should keep a large late commit deviation spread", failures)
	_assert_true(float(threshold_candidate.get("warning_band_upper_hint", 0.0)) - float(threshold_candidate.get("warning_band_hint", 0.0)) > 3.0, "warning threshold candidate should keep a large upper-center separation", failures)
	_assert_true(float(threshold_candidate.get("warning_band_hint", 0.0)) - float(threshold_candidate.get("warning_band_lower_hint", 0.0)) > 2.0, "warning threshold candidate should keep a large center-lower separation", failures)
	_assert_true(float(unified_warning_upper_threshold) - float(unified_warning_threshold) > 3.0, "warning unified snapshot should keep a large upper-center threshold spread", failures)
	_assert_true(float(unified_warning_threshold) - float(unified_warning_lower_threshold) > 2.0, "warning unified snapshot should keep a large center-lower threshold spread", failures)
	_assert_true(float(corridor_summary.get("claim_success_rate_mean", 0.0)) < float(funnel_summary.get("claim_success_rate_mean", 0.0)) and float(funnel_summary.get("claim_success_rate_mean", 0.0)) < float(orbit_summary.get("claim_success_rate_mean", 0.0)), "warning artifact should preserve claim success ordering in scenario summaries", failures)
	_assert_true(float(threshold_candidate.get("warning_band_upper_hint", 0.0)) == float(corridor_summary.get("p95_contention_mean", 0.0)), "warning upper hint should match corridor p95 mean", failures)
	_assert_true(float(threshold_candidate.get("warning_band_hint", 0.0)) == float(funnel_summary.get("p95_contention_mean", 0.0)), "warning center hint should match funnel p95 mean", failures)
	_assert_true(float(threshold_candidate.get("warning_band_lower_hint", 0.0)) == float(orbit_summary.get("p95_contention_mean", 0.0)), "warning lower hint should match dynamic_orbit p95 mean", failures)
	_assert_true(float(threshold_candidate.get("warning_band_upper_hint", 0.0)) > float(threshold_candidate.get("warning_band_hint", 0.0)) and float(threshold_candidate.get("warning_band_hint", 0.0)) > float(threshold_candidate.get("warning_band_lower_hint", 0.0)), "warning threshold candidate should preserve upper > center > lower ordering", failures)
	_assert_true(float(fitted_thresholds.get("warning_upper_threshold_value", 0.0)) == float(corridor_summary.get("p95_contention_mean", 0.0)), "fitted warning upper threshold should match corridor p95 mean", failures)
	_assert_true(float(fitted_thresholds.get("warning_threshold_value", 0.0)) == float(funnel_summary.get("p95_contention_mean", 0.0)), "fitted warning threshold should match funnel p95 mean", failures)
	_assert_true(float(fitted_thresholds.get("warning_lower_threshold_value", 0.0)) == float(orbit_summary.get("p95_contention_mean", 0.0)), "fitted warning lower threshold should match dynamic_orbit p95 mean", failures)
	_assert_true(float(fitted_thresholds.get("warning_upper_threshold_value", 0.0)) == float(threshold_candidate.get("warning_band_upper_hint", 0.0)) and float(fitted_thresholds.get("warning_threshold_value", 0.0)) == float(threshold_candidate.get("warning_band_hint", 0.0)) and float(fitted_thresholds.get("warning_lower_threshold_value", 0.0)) == float(threshold_candidate.get("warning_band_lower_hint", 0.0)), "fitted thresholds should match threshold candidate hints", failures)
	_assert_true(bool(gate_results.get("gate_b_warning_clumping_ordering", false)), "warning gate should report clumping ordering success", failures)
	_assert_true(bool(gate_results.get("gate_b_warning_latency_ordering", false)), "warning gate should report late commit deviation ordering success", failures)
	_assert_true(bool(gate_results.get("gate_b_warning_band_ordering", false)), "warning gate should report band ordering success", failures)
	_assert_true(bool(gate_results.get("gate_b_warning_overlap_ordering", false)), "warning gate should report overlap ordering success", failures)
	_assert_true(str(unified_snapshot.get("family", "")) == "warning", "warning artifact should persist unified snapshot family", failures)
	_assert_true(unified_thresholds.has("warning_upper_threshold_value"), "warning unified thresholds should keep upper threshold field", failures)
	_assert_true(unified_thresholds.has("warning_threshold_value"), "warning unified thresholds should keep center threshold field", failures)
	_assert_true(unified_thresholds.has("warning_lower_threshold_value"), "warning unified thresholds should keep lower threshold field", failures)
	_assert_true(unified_support_counts.has("nonzero_scenario_count"), "warning unified support counts should keep scenario count metric", failures)
	_assert_true(unified_gate_results.has("gate_b_warning_band_ordering"), "warning unified gate results should keep band ordering metric", failures)
	_assert_true(unified_gate_results.has("gate_b_warning_overlap_ordering"), "warning unified gate results should keep overlap ordering metric", failures)
	_assert_true(unified_gate_results.has("gate_b_warning_clumping_ordering"), "warning unified gate results should keep clumping ordering metric", failures)
	_assert_true(unified_gate_results.has("gate_b_warning_latency_ordering"), "warning unified gate results should keep latency ordering metric", failures)
	_assert_true(unified_warning_upper_threshold == float(fitted_thresholds.get("warning_upper_threshold_value", 0.0)), "warning unified snapshot should mirror fitted upper threshold", failures)
	_assert_true(unified_warning_threshold == float(fitted_thresholds.get("warning_threshold_value", 0.0)), "warning unified snapshot should mirror fitted center threshold", failures)
	_assert_true(unified_warning_lower_threshold == float(fitted_thresholds.get("warning_lower_threshold_value", 0.0)), "warning unified snapshot should mirror fitted lower threshold", failures)
	_assert_true(unified_takeover_ready == bool(gate_results.get("takeover_ready", false)), "warning unified snapshot should mirror gate takeover readiness", failures)
	_assert_true(unified_takeover_ready == bool(unified_gate_results.get("takeover_ready", true)), "warning unified snapshot should mirror nested gate takeover readiness", failures)
	_assert_true(unified_sample_count == int(sampling_results.get("sample_count_completed", -2)), "warning unified snapshot should mirror completed sample count", failures)
	_assert_true(unified_sample_count == int(gate_results.get("sample_count", -2)), "warning unified snapshot should mirror gate result sample count", failures)
	_assert_true(unified_sample_count == int(unified_gate_results.get("sample_count", -2)), "warning unified snapshot should mirror nested gate sample count", failures)
	_assert_true(unified_nonzero_scenario_count == int(sampling_results.get("nonzero_scenario_count", -2)), "warning unified snapshot should mirror nonzero scenario count", failures)
	_assert_true(float(unified_snapshot.get("confidence_score", -1.0)) == 1.0, "warning unified snapshot confidence score should remain normalized at 1.0", failures)
	_assert_true(float(unified_snapshot.get("confidence_score", -1.0)) >= 0.0 and float(unified_snapshot.get("confidence_score", -1.0)) <= 1.0, "warning unified confidence score should stay normalized", failures)
	_assert_true(Array(unified_snapshot.get("blockers", [])).is_empty(), "warning unified snapshot blockers should remain empty", failures)
	_assert_true(legacy_readiness_family == str(unified_snapshot.get("family", "")), "readiness snapshot should mirror unified family", failures)
	_assert_true(legacy_readiness_warning_upper_threshold == unified_warning_upper_threshold, "readiness snapshot should mirror unified upper threshold", failures)
	_assert_true(legacy_readiness_warning_threshold == unified_warning_threshold, "readiness snapshot should mirror unified center threshold", failures)
	_assert_true(legacy_readiness_warning_lower_threshold == unified_warning_lower_threshold, "readiness snapshot should mirror unified lower threshold", failures)
	_assert_true(legacy_readiness_takeover_ready == unified_takeover_ready, "readiness snapshot should mirror unified takeover readiness", failures)
	_assert_true(legacy_readiness_sample_count == unified_sample_count, "readiness snapshot should mirror unified sample count", failures)
	_assert_true(legacy_readiness_nonzero_scenario_count == unified_nonzero_scenario_count, "readiness snapshot should mirror unified nonzero scenario count", failures)
	_assert_true(legacy_readiness_family == "warning", "readiness snapshot should remain warning for compatibility", failures)
	_assert_true(legacy_readiness_sample_count == int(sampling_results.get("sample_count_completed", -2)), "readiness snapshot should still mirror completed sample count for compatibility", failures)
	_assert_true(legacy_readiness_nonzero_scenario_count == int(sampling_results.get("nonzero_scenario_count", -2)), "readiness snapshot should still mirror nonzero scenario count for compatibility", failures)
	_assert_true(legacy_readiness_takeover_ready == bool(gate_results.get("takeover_ready", false)), "readiness snapshot should still mirror gate takeover readiness for compatibility", failures)
	_assert_true(legacy_readiness_warning_upper_threshold == float(fitted_thresholds.get("warning_upper_threshold_value", 0.0)), "readiness snapshot should still mirror fitted upper threshold for compatibility", failures)
	_assert_true(legacy_readiness_warning_threshold == float(fitted_thresholds.get("warning_threshold_value", 0.0)), "readiness snapshot should still mirror fitted center threshold for compatibility", failures)
	_assert_true(legacy_readiness_warning_lower_threshold == float(fitted_thresholds.get("warning_lower_threshold_value", 0.0)), "readiness snapshot should still mirror fitted lower threshold for compatibility", failures)
	_assert_true(legacy_readiness_warning_upper_threshold > legacy_readiness_warning_threshold and legacy_readiness_warning_threshold > legacy_readiness_warning_lower_threshold, "readiness snapshot should preserve threshold ordering while remaining secondary", failures)
	_assert_true(legacy_readiness_nonzero_scenario_count == 3, "readiness snapshot should preserve the three-scenario support count for compatibility", failures)
	_assert_true(not legacy_readiness_snapshot.is_empty(), "readiness snapshot should remain populated for compatibility", failures)
	_assert_true(typeof(legacy_readiness_snapshot.get("family", null)) == TYPE_STRING, "readiness snapshot family should remain a string", failures)
	_assert_true(typeof(legacy_readiness_snapshot.get("takeover_ready", null)) == TYPE_BOOL, "readiness snapshot takeover readiness should remain a bool", failures)
	_assert_true(typeof(legacy_readiness_snapshot.get("sample_count", null)) == TYPE_INT or typeof(legacy_readiness_snapshot.get("sample_count", null)) == TYPE_FLOAT, "readiness snapshot sample count should remain numeric", failures)
	_assert_true(typeof(legacy_readiness_snapshot.get("nonzero_scenario_count", null)) == TYPE_INT or typeof(legacy_readiness_snapshot.get("nonzero_scenario_count", null)) == TYPE_FLOAT, "readiness snapshot support count should remain numeric", failures)
	_assert_true(typeof(legacy_readiness_snapshot.get("warning_upper_threshold_value", null)) == TYPE_INT or typeof(legacy_readiness_snapshot.get("warning_upper_threshold_value", null)) == TYPE_FLOAT, "readiness snapshot upper threshold should remain numeric", failures)
	_assert_true(typeof(legacy_readiness_snapshot.get("warning_threshold_value", null)) == TYPE_INT or typeof(legacy_readiness_snapshot.get("warning_threshold_value", null)) == TYPE_FLOAT, "readiness snapshot center threshold should remain numeric", failures)
	_assert_true(typeof(legacy_readiness_snapshot.get("warning_lower_threshold_value", null)) == TYPE_INT or typeof(legacy_readiness_snapshot.get("warning_lower_threshold_value", null)) == TYPE_FLOAT, "readiness snapshot lower threshold should remain numeric", failures)
	_assert_true(legacy_readiness_snapshot.size() >= 6, "readiness snapshot should remain populated with compatibility fields", failures)
	_assert_true(float(warning_summary.get("claim_success_rate_mean", 0.0)) > float(corridor_summary.get("claim_success_rate_mean", 0.0)) and float(warning_summary.get("claim_success_rate_mean", 0.0)) < float(orbit_summary.get("claim_success_rate_mean", 0.0)), "warning summary claim success mean should sit inside scenario bounds", failures)
	_assert_true(float(orbit_summary.get("claim_success_rate_mean", 0.0)) - float(corridor_summary.get("claim_success_rate_mean", 0.0)) > 0.25, "warning summary should be backed by a large claim success spread", failures)
	_assert_true(float(warning_summary.get("late_commit_deviation_mean", 0.0)) > float(funnel_summary.get("late_commit_deviation_mean", 0.0)) and float(warning_summary.get("late_commit_deviation_mean", 0.0)) < float(orbit_summary.get("late_commit_deviation_mean", 0.0)), "warning summary late commit mean should sit inside scenario bounds", failures)
	_assert_true(float(orbit_summary.get("arbitration_latency_mean", 0.0)) - float(funnel_summary.get("arbitration_latency_mean", 0.0)) > 0.7, "warning summary should be backed by a large latency spread", failures)
	_assert_true(float(corridor_summary.get("p95_contention_mean", 0.0)) - float(orbit_summary.get("p95_contention_mean", 0.0)) > 4.5, "warning artifact should keep a wide corridor-orbit p95 spread", failures)
	_assert_true(float(orbit_summary.get("late_commit_deviation_mean", 0.0)) - float(corridor_summary.get("late_commit_deviation_mean", 0.0)) > 0.9, "warning artifact should keep a wide late commit deviation spread", failures)
	_assert_true(float(warning_summary.get("late_commit_deviation_mean", 0.0)) > float(funnel_summary.get("late_commit_deviation_mean", 0.0)), "warning summary late commit mean should reflect stressed runtime separation", failures)
	_assert_true(float(threshold_candidate.get("warning_band_upper_hint", 0.0)) - float(threshold_candidate.get("warning_band_hint", 0.0)) > 3.0, "warning threshold candidate should keep a large upper-center separation", failures)
	_assert_true(float(threshold_candidate.get("warning_band_hint", 0.0)) - float(threshold_candidate.get("warning_band_lower_hint", 0.0)) > 2.0, "warning threshold candidate should keep a large center-lower separation", failures)
	_assert_true(float(unified_warning_upper_threshold) - float(unified_warning_threshold) > 3.0, "warning unified snapshot should keep a large upper-center threshold spread", failures)
	_assert_true(float(unified_warning_threshold) - float(unified_warning_lower_threshold) > 2.0, "warning unified snapshot should keep a large center-lower threshold spread", failures)
	_assert_true(float(unified_warning_upper_threshold) - float(unified_warning_lower_threshold) > 5.0, "warning unified snapshot should keep a wide threshold envelope", failures)
	var known_tail_items: Array = payload.get("known_tail_items", [])
	_assert_true(known_tail_items.size() == 2, "warning artifact should register the two known leak tail items", failures)
	return failures

func _assert_true(value: bool, message: String, failures: Array[String]) -> void:
	if not value:
		failures.append(message)
